### ISSUE TITLE
restore Aardvark.Rendering.NanoVg support

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#11]
GLContext/Glew currently fights on how to initialize gl entry points. To solve the issue we need to check how glew exactly works....

**Comment by krauthaufen** [comment]
I would say that this is rather impossible due to the new vulkan backend?
shall we drop support entirely?

**Comment by luithefirst** [comment]
Its still works on AMD for the GL backend, I also noticed that on a GTX980 I get OpenGL 4.3 and on AMD 4.5...

NanoVg has probably never been used for more than displaying the RenderStats, so no longer having that feature to plugin that easily is no good news, but providing an alternative with some SgText and a Quad would make up for that loss. Having a third party component that is messing with GL is not ideal in general, so lets get rid of it.
