### ISSUE TITLE
FSharp.Core version inconsistency

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.rendering#24]
FSharp.Quotations.Evaluator 1.0.7 is build with 4.3.1.0. This forces to use an app.config to fix the version to 4.4.0.0 for all Aardvark applications.

In the case Aardvark is used to extend a 3rd party application with a plugin that is executed in a predefined environment, using an app.config is not always possible (.dll.config is ignored)

**Comment by haraldsteinlechner** [comment]
we have this issue on for other 3rd party libraries as well. is there another chance than recompiling those libraries with other fsharp.core?

**Comment by haraldsteinlechner** [comment]
you're getting dllnotfound? i think the only options is using custom binding: http://stackoverflow.com/questions/31255666/how-do-i-redirect-assembly-binding-to-the-current-version-or-higher
seealso: https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#what-to-do-for-error-could-not-load-file-or-assembly-fsharpcore-version4000-or-similar

**Comment by krauthaufen** [comment]
Fixed by using packages
