### ISSUE TITLE
Uniformbuffers - Sparsebuffer implementation issues

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#32]
currently on some paltforms the sparsebuffer implementation does not work. For uniform buffers we currently deactivated spareBuffers, waiting for a better implementation.

**Comment by hyazinthh** [comment]
This has been resolved right? https://github.com/aardvark-platform/aardvark.rendering/commit/f23706ea1131f7c7c9330c5d9b6bcd5125f04c4d

 @luithefirst
