### ISSUE TITLE
Unable to load DLL 'glvm' or one of its dependencies

### ISSUE THREAD

**Issue by jackfoxy** [aardvark-platform/aardvark.rendering#51]
I created a netcoreapp2.2 project from the "first implementation" in the article https://rawgit.com/wiki/aardvark-platform/aardvark.docs/docs/media/Elmish.html
built with Aardvark.Base 4.5.15

I had to change the open statements in the entry point somewhat from the article in order to build.

```
open Aardvark.Base
open Aardvark.Base.Incremental
open Aardvark.Application
open Aardvark.Application.Slim
open Aardvark.SceneGraph
```

Builds, but reports missing DLL at runtime.

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'glvm' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

Executing in debug I get a different stack trace, which I believe is the correct stack trace and points to a C++ module in Aardvark.Rendering 4.11.7. 

```
at Aardvark.Rendering.GL.GLVM.hglCleanup(IntPtr ctx)
at Aardvark.Rendering.GL.ContextHandle.MakeCurrent()
at <StartupCode$Aardvark-Rendering-GL>.$Context.get_ResourceLock@285.Invoke(ContextToken x)
at Aardvark.Rendering.GL.ContextToken.Obtain()
at Aardvark.Rendering.GL.ContextToken..ctor(FSharpFunc`2 obtain, FSharpFunc`2 release)
at Aardvark.Rendering.GL.Context.get_ResourceLock()
at <StartupCode$Aardvark-Rendering-GL>.$ResourceManager.bufferMemory@24.Invoke(IntPtr size)
at Aardvark.Base.Management.ChunkedMemoryManager`1..ctor(Memory`1 mem, IntPtr chunkSize)
at Aardvark.Rendering.GL.UniformBufferManager..ctor(Context ctx)
at Aardvark.Rendering.GL.ResourceManager..ctor(FSharpOption`1 parent, Context ctx, FSharpOption`1 renderTaskInfo, Boolean shareTextures, Boolean shareBuffers)
at Aardvark.Rendering.GL.Runtime.set_Context(Context c)
at Aardvark.Application.Slim.OpenGlApplication..ctor(Boolean forceNvidia, Boolean enableDebug)
at Program.main(String[] argv) in C:\\Users\\jackf\\GitRepos\\AardvarkSandBox\\src\\DslFirstImplementation\\Program.fs:line 17
```

**Comment by luithefirst** [comment]
Could be a missing C++ runtime. I could not find that we list any prerequisites for that, but all native libraries such as Devil, Assimp, and our GL/VKVM need one.
In my application I check for:
msvcr120.dll / VS 2013
msvcp140.dll / VS 2015
Unfortunately I cannot exactly tell what runtimes are required for library. We should also add such checks to Aardvark for better error reporting. GLVM has been updated to VS2017 last year (I'm missing that). Could you please have a look what versions do you have installed?

**Comment by haraldsteinlechner** [comment]
newest glvm was updated to 19? @krauthaufen. my last build was 17 a month
ago which is standard on win10?

Christian Luksch <notifications@github.com> schrieb am Sa., 21. Sep. 2019,
10:30:

**Comment by haraldsteinlechner** [comment]
ah more likely the glsl compiler stuff

Harald Steinlechner <haraldsteinlechner@gmail.com> schrieb am Sa., 21. Sep.
2019, 12:54:

**Comment by krauthaufen** [comment]
@jackfoxy could try copying mscvrtXXX.dll next to your startup program and see if that resolves the issue?
Sadly I have no idea where to get those without installing the runtime...

a different path worth chasing would be to manually load the msvcrts using our DynamicLinker module.

Cheers

**Comment by jackfoxy** [comment]
I have several versions of the MS C++ redistributables installed. But I sure cannot find what fodders they get installed to. Searching across my entire disk for this file also yields nothing.

**Comment by krauthaufen** [comment]
If i recall correctly there was a tool for investigating this kind of bug. I'll ask one of our C++ experts and see if he can help us with that...
Just to be sure: you're running with 64 bits right?

**Comment by jackfoxy** [comment]
yes, 64-bit

**Comment by krauthaufen** [comment]
hey, sorry it took so long but basically the DependencyWalker (https://en.m.wikipedia.org/wiki/Dependency_Walker) should be capable of telling us which dll in the dependency tree cannot be loaded on your system.

If it actually tells us that some C++ runtime things are missing we could just bundle those with the affected dlls or at least put a note in our Readmes.

Would be great if you find the time to check it, since we couldn't reproduce the problem on any of our machines so far.

Cheers

**Comment by jackfoxy** [comment]
@krauthaufen  I was keeping my repo private because I have not synced the license file to the AardvarkPlatform license requirements. Hope you don't mind I just made it public to you can access the actual project involved.

https://github.com/jackfoxy/AardvarkSandBox/tree/master/src/DslFirstImplementation

Here are the results I got from loading the DslFirstImplementation.dll into DependencyWalker.

Error: At least one required implicit or forwarded dependency was not found.
Error: Modules with different CPU types were found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.


The following reported "Error opening file. The system cannot find the file specified(2)."

EXT-MS-WIN-RO-TYPERESOLUTION-L1-1-0.DLL
EXT-MS-WIN-RPC-SSL-L1-1-0.DLL
EXT-MS-WIN-RTCORE-GDI-DEVCAPS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-GDI-OBJECT-L1-1-0.DLL
EXT-MS-WIN-RTCORE-GDI-RGN-L1-1-0.DLL
EXT-MS-WIN-RTCORE-GDI-RGN-L1-1-1.DLL
EXT-MS-WIN-RTCORE-MINUSER-INPUT-L1-1-1.DLL
EXT-MS-WIN-RTCORE-MINUSER-PRIVATE-EXT-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-CURSOR-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-DC-ACCESS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-DPI-L1-2-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-DPI-L1-2-1.DLL
EXT-MS-WIN-RTCORE-NTUSER-IAM-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-INTEGRATION-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-SYNCH-EXT-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-SYSCOLORS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-SYSPARAMS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-WINDOW-EXT-L1-1-0.DLL
EXT-MS-WIN-SECUR32-TRANSLATENAME-L1-1-0.DLL
EXT-MS-WIN-SECURITY-AUTHZ-HELPER-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CAPAUTHZ-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CAPAUTHZ-L1-1-1.DLL
EXT-MS-WIN-SECURITY-CHAMBERS-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CREDUI-INTERNAL-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CREDUI-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CREDUI-L1-1-1.DLL
EXT-MS-WIN-SECURITY-CRYPTUI-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CRYPTUI-L1-1-1.DLL
EXT-MS-WIN-SECURITY-EFS-L1-1-0.DLL
EXT-MS-WIN-SECURITY-EFSWRT-L1-1-0.DLL
EXT-MS-WIN-SECURITY-EFSWRT-L1-1-1.DLL
EXT-MS-WIN-SECURITY-NGC-LOCAL-L1-1-0.DLL
EXT-MS-WIN-SECURITY-WINSCARD-L1-1-0.DLL
EXT-MS-WIN-SECURITY-WINSCARD-L1-1-1.DLL
EXT-MS-WIN-SESSION-USERMGR-L1-1-0.DLL
EXT-MS-WIN-SESSION-USERTOKEN-L1-1-0.DLL
EXT-MS-WIN-SESSION-WINSTA-L1-1-0.DLL
EXT-MS-WIN-SESSION-WTSAPI32-L1-1-0.DLL
EXT-MS-WIN-SETUPAPI-INF-L1-1-0.DLL
EXT-MS-WIN-SETUPAPI-INF-L1-1-1.DLL
EXT-MS-WIN-SHELL-DIRECTORY-L1-1-0.DLL
EXT-MS-WIN-SHELL-EMBEDDEDMODE-L1-1-0.DLL
EXT-MS-WIN-SHELL-SHELL32-L1-2-0.DLL
EXT-MS-WIN-SHELL-SHLWAPI-L1-1-0.DLL
EXT-MS-WIN-SHELL-TABBEDTITLEBAR-L1-1-0.DLL
EXT-MS-WIN-SHELL32-SHELLCOM-L1-1-0.DLL
EXT-MS-WIN-SHELL32-SHELLFOLDERS-L1-1-0.DLL
EXT-MS-WIN-SMBSHARE-BROWSERCLIENT-L1-1-0.DLL
EXT-MS-WIN-STORAGE-SENSE-L1-1-0.DLL
EXT-MS-WIN-STORAGE-SENSE-L1-2-0.DLL
EXT-MS-WIN-SXS-OLEAUTOMATION-L1-1-0.DLL
EXT-MS-WIN-TSF-MSCTF-L1-1-0.DLL
EXT-MS-WIN-TSF-MSCTF-L1-1-1.DLL
EXT-MS-WIN-UI-VIEWMANAGEMENT-L1-1-0.DLL
EXT-MS-WIN-USP10-L1-1-0.DLL
EXT-MS-WIN-WER-REPORTING-L1-1-0.DLL
EXT-MS-WIN-WER-UI-L1-1-0.DLL
EXT-MS-WIN-WER-XBOX-L1-1-0.DLL
EXT-MS-WIN-WEVTAPI-EVENTLOG-L1-1-0.DLL
EXT-MS-WIN-WINRT-DEVICE-ACCESS-L1-1-0.DLL
EXT-MS-WIN-WINRT-STORAGE-L1-1-0.DLL
EXT-MS-WIN-WLAN-ONEXUI-L1-1-0.DLL
EXT-MS-WIN-WLAN-SCARD-L1-1-0.DLL
EXT-MS-WIN-WWAN-WWAPI-L1-1-0.DLL
EXT-MS-WIN-WWAN-WWAPI-L1-1-1.DLL
EXT-MS-WINDOWSCORE-DEVICEINFO-L1-1-0.DLL
HVSIFILETRUST.DLL
IESHIMS.DLL

**Comment by krauthaufen** [comment]
Hey, could you also run the DependencyWalker on the failing library (glvm.dll) since I don't have a clue what it does with dotnet dlls?
our libraries don't really reference glvm.dll (which they can't since it's native) but instead DllImport it, which the DependencyWalker doesn't seem to understand...
Cheers

**Comment by jackfoxy** [comment]
This would be the very problem. There is no glvm.dll in any of my build artifacts.

**Comment by krauthaufen** [comment]
oh, okay you can take the one from the aardvark-rendering repo at https://github.com/aardvark-platform/aardvark.rendering/tree/master/lib/Native/Aardvark.Rendering.GL/windows/AMD64

**Comment by jackfoxy** [comment]
Copied all the glvm files to bin, and I believe that solves the immediate issue.

Now a new error:

````
 0: initializing OpenGL runtime ..............................................
 0:   vendor:   "NVIDIA Corporation"
 0:   renderer: "Quadro P4200 with Max-Q Design/PCIe/SSE2"
 0:   version:  OpenGL 4.3.0 / GLSL 4.3
 0: initializing OpenGL runtime ...................................... 0.370 s

Unhandled Exception: System.Exception: synthesized attribute "RenderObjects" for type Aardvark.SceneGraph.Sg+DynamicNode not found on path: Root
candidates: Semantic not found for name RenderObjects (m_semanticMap.Count=0).
Info about registered semantic functions:

at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
at Aardvark.SceneGraph.SceneGraphRuntimeExtensions.CompileRender(IRuntime x, IFramebufferSignature signature, BackendConfiguration engine, ISg s) in C:\Users\Schorsch\Development\aardvark.rendering\src\Aardvark.SceneGraph\RuntimeExtensions.fs:line 26
at Program.main(String[] argv) in C:\Users\jackf\GitRepos\AardvarkSandBox\src\DslFirstImplementation\Program.fs:line 26
````

**Comment by krauthaufen** [comment]
did you call `Ag.initialize()` and `Aardvark.Init()` in your startup code?
The problem seems to be related to our native dependency loading-mechanism. You could try upgrading to the latest Aardvark.Base version. We improved the loading of native dependencies and they should be automatically extracted to some temp folder when calling Aardvark.Init...
Hope that helps.
Cheers

**Comment by haraldsteinlechner** [comment]
Hi @jackfoxy,

i'm back and fixed your example in my PR.

- It has nothing to do with native dependencies at all :)
- The original code was missing `Aardvark.Init()` to initialize the attribute grammar 
- The original code was still missing application of the camera, already created in Program.fs

great effort btw!
