### ISSUE TITLE
Attaching 1 texture cube slice to a Framebuffer fails with vulcan runtime

### ISSUE THREAD

**Issue by StefanLeng** [aardvark-platform/aardvark.rendering#53]
Attaching one slice of a texture cube to a Framebuffer with runtime.CreateTextureAttachment(tex, int face) works as expected with an opengl backend, but fails on a vulcan backend with "ill-aligned cube-count 1"

The opengl  implementation in https://github.com/aardvark-platform/aardvark.rendering/blob/master/src/Aardvark.Rendering.GL/Resources/Framebuffer.fs eihter accepts 1 slice on a cubmap or  6.

The vulcan implementation in https://github.com/aardvark-platform/aardvark.rendering/blob/master/src/Aardvark.Rendering.Vulkan/Resources/ImageView.fs accepts only multiples of 6  as slices on a cube texture. (function viewType)

**Comment by hyazinthh** [comment]
Resolved in v51 branch (https://github.com/aardvark-platform/aardvark.rendering/commit/6dea6008e613b59acd34baf403acb6583d96df50)
