### ISSUE TITLE
move OutputMod module to central location

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.rendering#54]
When requiring custom OutputMods the already existing "module OutputMod" and "type OutputMod<'a, 'b>" seem practical functionality, but there are currently two implementations in non-central locations: "Demo\Examples\Stereo.fs" and "Application\Aardvark.Application.Utilities\Window.fs"

This functionality should be cleaned up and moved to a central location.

**Comment by hyazinthh** [comment]
As far as I can see, the existence of the `OutputMod` type and module is merely a symptom of another issue: Missing functionality to create adaptive texture arrays (for stereo rendering), and adaptive textures with the possibility to specify the number of mip levels (in Aardvark.Docs/src/Sky/App.fs)

I've added overloads for these use cases (and others) to the `ITextureRuntime` interface in the cleanup branch (https://github.com/aardvark-platform/aardvark.rendering/commit/327775454704d2b844e957677fe62743697b56d8), and replaced the `OutputMod` uses with calls to the new methods. In my opinion, the `OutputMod` type was flawed to begin with, as it tried to be as general as possible (i.e. representing any kind of resource) while also covering very specific use cases. This resulted in quite verbose code, while also being restrictive in what you could do with it.

For the future, if similar use cases for adaptive resources pop up that are not covered by the 
 corresponding runtime interface, I suggest the following approach:
- If the use case is common, a new overload for the runtime interface should be implemented.
- If the use case is very specific and special, simply overload the `AbstractOutputMod` type. This type is more general than the `OutputMod` type and is probably an appropriate starting point in most scenarios.

What do you think?
