### ISSUE TITLE
rework IndirectBuffer API

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.rendering#57]
There are two uses cases that we want to support: 
1. ArrayBuffer of DrawCallInfos 
2. BackendBuffer that should be untouched

The difficulty is **(A)** that the graphics API requires a different DrawCall layout depending on whether the buffer is used for Indexed or Non-Indexed rendering. Luckly GL and Vulkan have the same layout, but technically it is a backend specific detail that **(B)** is ideally abstracted away from the user.

Currently IIndirectBuffer is defined as:
```
type IIndirectBuffer =
    abstract member Buffer : IBuffer
    abstract member Count : int
```

The latest sketch replaced this by:
```
type IndirectBuffer(b : IBuffer, count : int, stride : int, indexed : bool) =
    member x.Buffer = b
    member x.Count = count
    member x.Stride = stride
    member x.Indexed = indexed
```

Now everything for the BackendBuffer case can be also specified, but _Stride_ and _Indexed_ would not be necessary when using an ArrayBuffer.

_Indexed_ would actually only be a validation parameter.

I would suggest to get rid of these parameters again and also keep the non-interfaces type. We could assume a fixed stride of 16 for non-indexed and 20 for indexed and that the data is properly layouted? Do we want to support a user specified stride?

The behavior in case of a NativeBuffer and SingleValueBuffer is also not specified clearly. After we have decided how to rework this, we should add some comment to document this.

To address **(B)** we could introduce a special kind of IBackendBuffer (e.g. IBackendIndirectBuffer) and provide specialized update functionality via the runtime API.

IBackendIndirectBuffer should ideally inherit IBackendBuffer so it can be used in the same way other buffers. It could also be the place where to add the _Stride_ and _Indexed_ properties. 

Suggestion of new IndirectBuffer:
```
// Indirect buffer data declaration to be used on the scene graph and RenderObject
type IndirectBuffer(b : IBuffer, count : int) =
    member x.Buffer = b
    member x.Count = count
```

Suggestion of IBackendIndirectBuffer:
```
// augmented IBackendBuffer to support 
type IBackendIndirectBuffer = 
    inherit IBuffer
    abstract member Stride : int
    abstract member Indexed : bool
```

Suggestion of additional IBufferRuntime methods:
```
// make an already existing buffer compatible to be used as IBackendIndirectBuffer with a custom stride
abstract member CreateIndirectBuffer : data : IBackendBuffer * indexed : bool * stride : int -> IBackendIndirectBuffer

// creates a indirect buffer -> updates will properly write the DrawCall depending on indexed option
abstract member CreateIndirectBuffer : size : nativeint * indexed : bool -> IBackendIndirectBuffer

// upload indirect buffer data
abstract member Copy : srcData : DrawCallInfo[] * dst : IBackendIndirectBuffer * dstOffsetCount : nativeint * count : nativeint -> unit
```

Things to note:
1. In the case an already existing IBackendBuffer is wrapped with a non-standard stride, this would need to be considered when using Copy.
2. In case an IBackendBuffer is used in IndirectBuffer no validation of indexed property is possible, default stride depending on use case will be assume.

**Comment by luithefirst** [comment]
GL: glDrawElementsIndirect, glDrawArraysIndirect
Vulkan: vkCmdDrawIndirect, vkCmdDrawIndexedIndirect
DX11: DrawInstancedIndirect, DrawIndexedInstancedIndirect

Both have the same 16 byte and 20 byte layout for non-indexed and indexed drawing and support a stride. This might be useful to interleave the drawbuffer with information that can be used for optional compute shader processing.
I would say that we do not essentially need to support a custom stride, but then I would specify that the buffer has to have tightly packed draw commands in the layout the graphics API also use, so if someone uses this feature "blindly" can assume how to fill the buffer.

In the glvm the stride is hardcoded to 20 for non-indexed and 0 for indexed (assumes tightly packed commands). Passing the stride could be implemented straight forward by extended the HandleAndCount struct.
In the vkvm the stride is currently also hardcoded to 20.

DX12 already has next level functionality with ExecuteIndirect:
https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-executeindirect

- Execute several Draw, DrawIndexed or Dispatch calls in one go
  - It‘s more a MultiExecuteIndirect()
- Inbetween Draws/Dispatches:
  - Change Vertex and/or Index Buffer (also prim count)
  - Change root constants and root CBVs
  - Change root SRVs and UAVs

Independent on how we decide to proceed with this rework, considering future extension towards DX12 functionality should be kept in mind.

**Comment by luithefirst** [comment]
In Vulkan (and DX) a buffers needs to be created with a certain usage flags, so an IBackendBuffer cannot be used arbitrarily. -> what should CreateBuffer do !?

We could add usage flags to the arguments (Vertex/Index/Indirect/..)
Or we could define specialized functions per type. In case of the IndirectBuffer a stride could be allowed as extra argument, that would not make sense for the other.

Separating BackendBuffers by usage type implies that an IBackendBuffer should not be allowed to be used same as IBuffer. An IBuffer currently can be "backend", "array", "singleValue", "native"...
Do we want to express this restriction already in the type system/interfaces?

**Comment by krauthaufen** [comment]
Our historical approach to these things was just adding all usage flags for each buffer/texture essentially...
This may impose performance penalties but my (very informal) tests back in the day didn't show any...
However some things might actually limit functionality (e.g. most buffer formats won't allow to be used as indirect buffers).
So I'm generally positive on adding these flags, but when we do we should also add them to textures/images.

**Comment by luithefirst** [comment]
Changes implemented in v5:
* Optional buffer usage flags in IBufferRuntime
* New IndicirectBuffer with support of stride:
```
type IndirectBuffer(b : IBuffer, count : int, stride : int, indexed : bool) =
    member x.Buffer = b
    member x.Count = count
    member x.Stride = stride
    member x.Indexed = indexed
```
Handling of ArrayBuffer and IBackendBuffer are implemented in the ResourceManager. ArrayBuffers still require a `DrawCallInfo[]` and consider the `Indexed` argument when uploading the data. They always use a stride of 20 bytes. The `Indexed` argument in the case of an IBackendBuffer is only used for validation.
