### ISSUE TITLE
RenderTask.Dispose needs transaction

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#60]
should not be the case, workaround in media v5

**Comment by haraldsteinlechner** [comment]
see: https://github.com/aardvark-platform/aardvark.media/commit/a96c6b011f60d7f1afcefbfc546e5c1e57bbfa44

**Comment by hyazinthh** [comment]
Fixed in b2d534886817b14a09df43b2b33839399a15ab4e
