### ISSUE TITLE
QueryObjects API

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.rendering#61]
We need to abstract this functionally behind our rendering API in order to provide all functionality required for my application: https://www.khronos.org/opengl/wiki/Query_Object

The `IRuntime` should allow creating Queries:
* Time
* SampleCount
* PrimitiveCount
* (AnySample)
* (TimeStamp)

Using a `long` as result for all types is possible.

Questions:
* Should creating a Query also invoke a Begin or should this be separate? Actually, I like the idea of reusing queries (even they need to be re-created in GL) so a separate Begin/Start seems convenient.
* Should it be a `Disposable` or cleaned up by Runtime.DeleteQuery (like with textures)? -> It looks we chose this pattern for textures/buffers in order to allow resource management/counting. I would say we can go for a Disposable here.
* Should there be a mechanism to detect conflicts of nested queries of the same type (not supported by OpenGL)?

A query should allow:
* IRuntime.CreateQuery
* Begin/Start
* End/Stop
* HasResult: check if there is a result
* TryGetResult: get result if available
* GetResult: waiting for the result with an optional timeout
* Dispose
* Restart

What about advanced features/interoperability with RenderCommands?
* Feed PrimitiveGenerated to an indirect render command
* Conditional rendering using AnySample

Already found in the GL backend:
* `GLTimer` in Configfs.
* `OpenGlStopwatch` in Config.fs
* `OpenGlStopwatch` in Statistics.fs
* `OpenGlQuery` in Statistics.fs: Already looks like a usable abstraction of a query, but missing e.g. TryGetResult, silently ignores nested queries?

**Comment by hyazinthh** [comment]
Implemented queries in https://github.com/aardvark-platform/aardvark.rendering/commit/c87eee3f91b597d2c6e9c16d48c683f360b26959
