### ISSUE TITLE
Allow WriteBuffers attribute to be dynamic

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.rendering#63]
The colorMask, depthMask, stencilMask and drawBuffers are defined by the WriteBuffers scene graph attribute which is constant. It would be nice to allow toggling this option and thereby avoiding structural changes or duplicated render tasks to achieve this.

Simply changing it to `cval`/`aval` should already allow this. The ResoureceManage would then also need to include caching for derived computations to allow sharing (e.g. similar to `getTessDrawModeCache`). Redundancy removal should then result in single global attributes if also only one such is applied to the scene graph.

Georg mentioned that there might be issues with ´BackLeft´ and ´ColorAttachment0´. -> Render to window or texture?
Caching of the drawBuffer computation also needs the signature as input?

Use Case 1: DepthWrite on/off for optional Z-Pre Pass
Task 1 Depth with DepthTestMode=Less and simplified scene graph and no overhead of producing color
Task 2 Depth/Color with DepthTestMode=Equal and Write only to Color

If Z-Pre is deactivated, Task 1 is skipped and Task 2 needs to change DepthTestMode to Less (no problem) and enable Depth Write (not possible)
At the moment this would require a 3rd task for adding WriteBuffer Depth or ignoring disabling Depth Write in Task 2 and having unnecessary overhead when z-pre is activated.

Use Case 2: Optional Output Layer e.g. Normals
Write to Normal buffer should be optional

Issue 1: Signature needs to be constant, so even if the normal buffer is not used, it needs to be supplied in the OutputDescription. -> System would require unnecessary texture memory if the feature is deactivated, but there are cases where this is acceptable.
Issue 2: Shader switch can only simplify calculation of output attribute (returning default value), but the output will still be generated. -> I assume this would not have a high impact.

Still, in certain scenarios, I re-compile RenderTasks with an updated Signature and specialized shaders to toggle optional outputs. -> This is only feasible if used low-frequency. Introduce RenderTask.ReCompile/ChangeSignature for a faster updates?

Conclusion: It becomes clear that there is actually a difference in ColorMask/DepthMask/StencilMask and DrawBuffers. Toggling the masks should be flexible while changing general draw buffers typically have more implications. At the moment we only have a WriteBuffers attribute. Maybe we want to keep the WriteBuffers immutable (maybe rename to OutputBuffers) and extend it with adaptive WriteMask attributes. This way we can also add support for actual mask values for color and stencil.

Additional Note: ColorMask and BlendMode would also be possible per DrawBuffer

**Comment by hyazinthh** [comment]
Fixed as part of pipeline state rework in https://github.com/aardvark-platform/aardvark.rendering/commit/49138c61ae309f505c037df6b161222ac801e8d2

**Comment by luithefirst** [comment]
NOTE: 

Internally implemented with DepthWriteMask + StencilWriteMask + ColorWriteMask per Layer and separate scene graph applicators for each

Sg.writeBuffers is a convenience abstraction and applies Sg.depthWrite + Sg.stencilMask + Sg.colorWrites by decomposes its arguments -> Sg.writeBuffers is not composable with additional Sg.depthWrite/stencilMask/colorWrites applicator
