### ISSUE TITLE
Shader caches do not work as intended with IFrameBufferSignature

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.rendering#68]
The OpenGL shader caches in Program.fs (https://github.com/aardvark-platform/aardvark.rendering/blob/master/src/Aardvark.Rendering.GL/Resources/Program.fs#L430)
either use `(string * IFrameBufferSignature)` or `(Effect * IFrameBufferSignature)`. A FrameBufferSignature is created per RenderControl and if not cached in the application it might also be created redundantly in RenderToTexture use cases. 
It looks like the shader caches should be dependent on the structure of the AttachmentSignatures rather than the actual FramebufferSignature.

We could consider using a custom `EqualityComparer`. There also is an almost complete `IsAssignableFrom`.

**Comment by luithefirst** [comment]
There are also other methods like `IRuntime.AssembleModule` with a dependency on `IFrameBufferSignature`, so we have the same behavior there. 

We are actually missing a cache in `CreateFrameBufferSignature`.

**Comment by hyazinthh** [comment]
Should be fixed by https://github.com/aardvark-platform/aardvark.rendering/commit/50dfe096acfe6fc6b121b95f84a1b233ab6402c9
