### ISSUE TITLE
ResourceManagement related/RenderTask run related concurrency issues

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#69]
there are rare race conditions in ResourceManagement, most likely revealed with locking changes in adaptive (can be seen here: https://github.com/aardvark-platform/aardvark.rendering/commit/31020744b37c388e9d5006940a374e937b03f3a7)

- [x] Vk: eager destroy does  clearly races with execution. proposal for the fix is here: 76954337feeb169dd02be96b41722b99a5432d7e
- [x] GL and VK: Prepare/DisposeRenderobject is currently not threadsafe `prepareIt = true` (for example drawInfo resources suffer from races -> crazy behaviour or segfaults in glvm). In Vk it is sometimes observable with refcounts being << 0. proposed fix in: 30505d894b79c7b6b06e49fe412d547d03cdb7b7
- [ ] unclear, no repro for this one, https://github.com/aardvark-platform/aardvark.rendering/commit/fb873f7b3de891c36a970d6d8059e3f2e8ac9a16

**Comment by haraldsteinlechner** [comment]
let prepareIt = true  // VK: fail; GL: OK
    let inlineDispose = true // OK
    let perObjTexture = true // OK
    let prepareTexture = true // GL: OK, Vk: only works with dubios 4089ebc1 fix
    let addRemoveTest = true // OK
    let textureTest = true // OK
    let jitterFrames = true // OK

**Comment by hyazinthh** [comment]
The concurrency test example revealed another issue with how resources are updated in the Vulkan backend. In summary, the problem is that in concurrent scenarios there is a chance that a single resource is updated multiple times within the resource update loop of a `CommandTask`. This can lead to deleted handles (due to recreation) being referenced in the command buffer that is filled during that update loop.

https://github.com/aardvark-platform/aardvark.rendering/commit/c1f57da627fe3f5e7256eff404f7fd244cf538f8 on the v51 branch addresses this by delaying concurrent updates while the main thread is within the resource update loop. I'm not sure if this can potentially lead to other problems, so far it seems to work as intended.

**Comment by hyazinthh** [comment]
After further investigation, it is evident that the fix in https://github.com/aardvark-platform/aardvark.rendering/commit/c1f57da627fe3f5e7256eff404f7fd244cf538f8 does not solve all our issues. The asynchronous nature of Vulkan along with the strict synchronization requirements make it probably impossible to ensure only a single handle of a resource is allocated at a time. Simply put, as long as a handle of a resource is bound in a descriptor set or referenced in an unexecuted command buffer, the handle must not be deleted even if it is out of date and another handle is created.

The only solution I see at this point is to use reference counting for the relevant resources to keep track if their handles are being used and delay their disposal if that is the case. The good news is that this solution seems to work as I've managed to run the full ConcurrencyTest example without any problems in an early test. Implementing this properly, will take some more time however.

So far, I've identified the following resources to absolutely require reference counting:
  - `Image`
  - `ImageView`
  - `Sampler`
  - `Buffer` (vertex, index, storage buffers?)

**Comment by hyazinthh** [comment]
```
let prepareIt = true       // OK
let inlineDispose = true   // OK
let perObjTexture = false  // OK
let prepareTexture = false // GL: OK, Vk: Fail (Copy engine sync issue?, sync upload works, how does 4089ebc1 fix relate to this?)
let addRemoveTest = true   // OK
let textureTest = true     // OK
let jitterFrames = false   // OK
```

**Comment by haraldsteinlechner** [comment]
wow!

**Comment by hyazinthh** [comment]
```
let prepareIt = true       // OK
let inlineDispose = true   // OK
let perObjTexture = true   // OK
let prepareTexture = true  // OK
let addRemoveTest = true   // OK
let textureTest = true     // OK
let jitterFrames = false   // OK
```
