### ISSUE TITLE
Remove/Skip SceneGraphCompletenessCheck

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.rendering#71]
At the moment we always perform a `SceneGraphCompletenessCheck` using the `OnAardvarkInit` attribute. In examples of Aardvark.Rendering it takes about 100ms and in my application 250ms in the best case after a repeated start and a little bit longer otherwise. For me, it is not reasonable to run this test on every application startup or even at all. I would like to discuss possibilities to change this behavior:
1. Allow running the check manually on startup: I would prefer that
2. Only include in DEBUG builds: (-) debug build needs to be installed manually
3. Add an option to skip or opt-in on this test: like (1) requires knowledge that this option exists, but if we choose to opt-in, directly running the method instead of setting a bool would be better
4. Use a cache file to determine if this test has already been performed: (-) most implementation effort and I/O overhead

I don't think that extending Sg rules is an everyday task and when actually working on them I would assume that the runtime error should point in the right direction and the developer can run this check manually.

**Comment by krauthaufen** [comment]
Seems reasonable to me, so basically we can just omit the `OnAardvarkInit` attribute there

**Comment by krauthaufen** [comment]
Especially since it only checks whether rules for the built-in Sg types exist

**Comment by luithefirst** [comment]
Maybe we could also integrate this into a unit test if it makes sense? However, it would only include types in aardvark rendering, but I think the purpose is to check for issues with extensions defined on the application side.

**Comment by krauthaufen** [comment]
No it actually only checks things defined in Aardvark.SceneGraph afaik, so i think it should really be a unit-test

**Comment by hyazinthh** [comment]
Moved to unit test in https://github.com/aardvark-platform/aardvark.rendering/commit/1dada47f4acde7a8209bd95c888b4b0d354b5654

**Comment by luithefirst** [comment]
Nice! Finally a working unit test again :D
