### ISSUE TITLE
Proper support for fast, hardware-supported compressed texture formats from file

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#80]
From functionality something like DDS would be neat. DDS is not the best choice, since all is compressed and it is rather old. There are some newer options, such as https://github.khronos.org/KTX-Specification/

The idea would be:

- fast loading from disk/stream
- direct support at graphics api level (no decompression needed when used as texture)
- precomputed mips
- decompression method to use convert it to piximage (also fallback if hardware compression method is not supported)

Maybe we find a nice library making this easy. The spec looks feasable also.
💯 

edit: maybe this could be a library `Aardvark.PixImage.KTX` or something like this..

**Comment by krauthaufen** [comment]
Hey, good idea, these standard block-compressions should be fairly easy to implement, so maybe doing that ourselves is also an option here

**Comment by luithefirst** [comment]
This would also allow for some improvements in my application. There it is possible to enable texture compression, but then the scene loads much slower as the compression is done on the fly and it does not seem very fast. Directly uploading compressed textures (+mip maps) would be a nice improvement.

**Comment by hyazinthh** [comment]
This is implemented for a while now (for DDS and BC1-5). Supports direct upload to the GPU (including mip maps) as well as host-side encoding (on-the-fly compression) and decoding (downloading compressed textures).
