### ISSUE TITLE
switch to official (new) AssimpNet

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#81]
our current unofficial assimpNet has several issues:

- old
- no proper standalone builds for windows
- no (portable) build for osx

we could switch to this one: https://www.nuget.org/packages/AssimpNet/5.0.0-beta1 or combine it with our dependency mechanism. please note that this is based on a different repo as a whole: https://bitbucket.org/Starnick/assimpnet/src/master/

**Comment by haraldsteinlechner** [comment]
i just tried several things - native dependency loading is super sophisticated in assimpnet to work on all platforms including unity - and the builds are far from standalone. given this i would not mess around with runtime unpacking and just use it. 

advantage:

 - works
 - no additional repo/different efforts

disadvantage:

- build task with all runtimes living beside compile target:
![image](https://user-images.githubusercontent.com/513281/126353117-98be9511-3942-4606-bb5d-4fd55480f47e.png)

**Comment by haraldsteinlechner** [comment]
seems painless - https://github.com/aardvark-platform/aardvark.rendering/commit/72d033da2022d3b023bed8372ec3a6019715c547

how does this affect deployments? at least for interactive sessions we would need an aardvarky solution via depenency unpacking?

**Comment by haraldsteinlechner** [comment]
in pro3d for example deployment seems fine https://github.com/pro3d-space/PRo3D/issues/69

**Comment by hyazinthh** [comment]
I've created a [fork of AssimpNetter](https://github.com/aardvark-community/aardvark.data.assimp) with Aardvark-style library loading since the original AssimpNet has been abandoned.

We'll switch to that one with Aardvark.Rendering 5.6.

**Comment by ibrahim324** [comment]
I didn't find an official roadmap for aardvark.rendering, when can I expect the switch?

**Comment by haraldsteinlechner** [comment]
Would it be better to move assimp to aardvark.data to uncouple it from rendering and to underline it is just a data to scenegraph transformation? Then also multiple approaches could co-exist?

**Comment by ibrahim324** [comment]
Thanks fellas!

**Comment by haraldsteinlechner** [comment]
Ahh because aardvark.scenegraph.assimp is still in rendering. Could this move out too?

**Comment by hyazinthh** [comment]
The examples use it, that would introduce some weird circular dependency.
