### ISSUE TITLE
MoltenVK support

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#83]
our moltenvk branch currently fails since the window handle was not created with metal layer - a similar error can be seen here: https://github.com/KhronosGroup/MoltenVK/issues/78

We tried:
 - use glfw to selectively create the surface: not possible since we have no glfw window and cannot fake it easily
 - use a special entry point in vkvm to patch the surface - https://github.com/KhronosGroup/MoltenVK/issues/78#issuecomment-371118536 - could not make compile the function there

the branch with some fixes can be found here: https://github.com/aardvark-platform/aardvark.rendering/tree/moltenvk

maybe moving to glfw generally could be the solution (we could also get rid of opentk there).

related: https://github.com/aardvark-platform/aardvark.rendering/issues/82

**Comment by krauthaufen** [comment]
The OpenGL GLFW stuff should be fairly easy to port for vulkan I think.
I just never did it because "vulkan doesn't work on Macs anyway"

**Comment by krauthaufen** [comment]
Working in glfw-vulkan branch and will be released in v52 by @hyazinthh right?

**Comment by hyazinthh** [comment]
Already merged into v52

**Comment by krauthaufen** [comment]
Cool, so I'll close this
