### ISSUE TITLE
Text with backface culling

### ISSUE THREAD

**Issue by luithefirst** [aardvark-platform/aardvark.rendering#91]
The Aardvark text cannot be used with Backface culling. A text intended to be only visible from one side. It seems the triangle winding order is not consistent. 

Steps to repdoruce: 
- go to example "Scratch (netcore) / 04 - ManyTexts"
- set `flipViewDependent` to `false`
- add `Sg.Cullmode' Cullmode.Back`

Result (showing front- and backside):
![image](https://user-images.githubusercontent.com/8556777/164234200-f7b2b8d6-710f-49da-a9fb-5485709e6445.png)

It would be nice if texts could be used with CullMode or any other mechanism to create one-sided texts. Thanks!

**Comment by hyazinthh** [comment]
I've implemented a simple workaround that flips triangles that have the wrong winding order here: https://github.com/aardvark-platform/aardvark.rendering/blob/838dfecdcb9989a0dc3d2c3bb0ddc7f7ec012cec/src/Aardvark.Rendering.Text/PathTessellator.fs#L1013

This resolves the issue for the most part, some very minor shimmering artifacts remain. When switching to `FillMode.Line` it becomes apparent that these are the result of some degenerated triangles: ![Untitled](https://user-images.githubusercontent.com/39337420/168851664-3a5c3b86-ace4-496c-b773-1db836dedd0b.png)

I'm not sure know how and where these can be discarded.

**Comment by hyazinthh** [comment]
Added a simple filter that removes most of the artifacts. The chosen epsilon is small, so this should not result in holes or similar artifacts.
