### ISSUE TITLE
HideCocoaToolbar got lost?

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#92]
previously this was a global value, now it always `false`.
bring back configuration possiblity using global variable or argument to OpenGlApplication (which would be breaking).

seealso: https://github.com/aardvark-platform/aardvark.rendering/commit/fd37cdb6c99dc9e1e73d1d0aa9aa7fdf3d610674#r71813287

**Comment by hyazinthh** [comment]
We could add another constructor if we need this with a minor version bump.

**Comment by hyazinthh** [comment]
I've added a new constructor, for the next major version we should consider using optional parameters. Its getting a bit messy otherwise.
