### ISSUE TITLE
New assembler crashes on M1 in x64

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#96]
Seems new after updates, in PRo3D on Mac M1 running in rosetta we get:
![Screenshot 2022-08-25 at 09 09 07](https://user-images.githubusercontent.com/513281/186598956-75c29fab-f239-4df8-9579-9b5d7820cec7.png)

@krauthaufen this is a new assembler which got active, right? could one switch to real ARM64 yet?  https://github.com/pro3d-space/PRo3D/issues/197

**Comment by krauthaufen** [comment]
So far everything worked on ARM64, so I think we could give it a try

**Comment by haraldsteinlechner** [comment]
it is a lot of work to get native arm64 though. ideas why x64 is broken? it might also be broken on native x64 Macs?

**Comment by haraldsteinlechner** [comment]
seems like `eiswriteable` is not available in jitmem. is this just a wrong version being used or something?

**Comment by krauthaufen** [comment]
Looks like it, i added the entrypoint in one of the last versions

**Comment by krauthaufen** [comment]
Maybe there was a broken version which got resolved at your end? Is there a newer one?

**Comment by haraldsteinlechner** [comment]
i is 5.2.12 rendering. if there is a newer one maybe @LauraFritz or @hyazinthh could upgrade. i need to hand this one over... thanks you all

**Comment by haraldsteinlechner** [comment]
https://github.com/pro3d-space/PRo3D/blob/develop/paket.lock assembler is 0.0.7 btw

**Comment by haraldsteinlechner** [comment]
ah and another info. on win this exact build works...

**Comment by krauthaufen** [comment]
Maybe related: https://github.com/aardvark-platform/aardvark.docs/issues/34

**Comment by haraldsteinlechner** [comment]
fix for amd64 Mac is in the assembler package, not sure about deployment though

**Comment by haraldsteinlechner** [comment]
status:

- aardvark.assembler 0.0.7, the embedded version has eiswriteable
- pro3d is using 0.0.7
- yet is seems to load a native lib which is packaged in aardvark.rendering according to this output

```
 6: [Introspection] loaded native library jitmem.dylib from /var/folders/ls/fc80rh9d40vbtn23g92pvcjh0000gn/T/aardvark-native/Aardvark.Rendering.GL-04c7c946-bb69-d9ba-c36b-1d07d22d1550-64/libjitmem.dylib
 6: [Introspection] loaded native library jitmem from jitmem.dylib
 6: ERROR
 6:   [Client] 2: rendering faulted with System.TypeInitializationException: The type initializer for 'Aardvark.Assembler.JitMem' threw an exception.
 6:    ---> System.TypeInitializationException: The type initializer for '<StartupCode$Aardvark-Assembler>.$JitMem' threw an exception.
 6:    ---> System.EntryPointNotFoundException: Unable to find an entry point named 'eiswritable' in shared library 'jitmem'.
 6:      at Aardvark.Assembler.JitMem.eiswritable()
 6:      at <StartupCode$Aardvark-Assembler>.$JitMem..cctor()
 6:      --- End of inner exception stack trace ---
 6:      at Aardvark.Assembler.JitMem..cctor()
 6:      --- End of inner exception stack trace ---

```

shouldn't this one be unpacked from aardvark.assembler? it seems to be using rendering 5.2.12. could rendering upgrade just fix this one? https://github.com/pro3d-space/PRo3D/issues/227

**Comment by haraldsteinlechner** [comment]
it seems like this aardvark.rendering version is taking jitmem.dylib from aardvark.rendering instead of aardvark.assembler - 5.3 prerelease track could fix this issue, unfortunately pro3d is blocked. what is the last eiswritable free version to downforce rendering? other option would be to backport the new assembler to non 5.3 or upgrade pro3d to 5.3

**Comment by krauthaufen** [comment]
The rendering dylib shouldn't exist anymore, so we can just remove it and publish a new minor rendering version?

**Comment by haraldsteinlechner** [comment]
yes, was already done, created a new package. works
