### ISSUE TITLE
cannot create application [Framebuffer] samples must be one of set [1; 2; 4; 8; 16; 32; 64] but got 0

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#97]
in pro3d we have this stack trace.
https://github.com/pro3d-space/PRo3D/issues/235

analysis so far :

1. those prints are not printed - - happen afterwards?
2. it is a managed validation problem 
3. the cause might be 0 being returned here: https://github.com/aardvark-platform/aardvark.rendering/blob/e5f3b7e0a8dc3777180c27ce1e82cb8509a68e8e/src/Application/Aardvark.Application.Slim.GL/Application.fs#L232 -- or there is a driver issue, but since (1) is not printed we have no idea about this

@hyazinthh --- do you have any ideas?

**Comment by hyazinthh** [comment]
Are you using Aardvark.Rendering >= 5.2.5? Prior to that we always called `GetFramebufferParameter` even if it wasn't supported (https://github.com/aardvark-platform/aardvark.rendering/commit/7378aadc8a659047ed78354b91120fac8be41306)

If that's not it, it might be a driver bug as far as I can see.

**Comment by haraldsteinlechner** [comment]
1. could we somehow achieve opengl version being printed reliably before stuff like this could happen? 
2. shall we min(1,x) the reuslt from GetFramebufferParameter for robustness?

**Comment by hyazinthh** [comment]
1. It should print "OpenGL 4.x working" when the context is created.
2. Probably check if the result is a valid sample count, and return `None` if it isn't.

**Comment by haraldsteinlechner** [comment]
the crash seems to happen before the context is created? at least in the logs it looks liek this
agree for (2).

**Comment by hyazinthh** [comment]
The sample count is queried when the surface is created, which happens after context creation.

**Comment by haraldsteinlechner** [comment]
ahh and yes it is rendering 5.2.12 - so, no idea why the problem appeared *now*.

**Comment by haraldsteinlechner** [comment]
yet, i still think this is *not* a driver bug as such but opengl might just generate an error. Just not checking errors in production might be a bad idea? https://github.com/aardvark-platform/aardvark.rendering/blob/db2ed7a17b43842d766e1832b034d063135711b8/src/Aardvark.Rendering.GL/Core/Config.fs#L124

how about at least emiting to log file for diagnosis instead of swallowing all opengl errors. 
Just to improve production error diagnosis. what do you think?

**Comment by hyazinthh** [comment]
That flag is controlled via the debug level / flag of the runtime, i.e. it is set to `Exception` when the runtime is created with `DebugLevel.Normal` or higher. So errors are checked if the application is created with `debug = true`.

I think it's enough to do a sanity check on the output, if that call generates an error or returns garbage it must be a driver bug of some sort.

**Comment by hyazinthh** [comment]
Actually, it seems like zero is a valid query result:

>If a framebuffer object is not framebuffer complete, as defined in section 9.4.2, then the values of SAMPLE_BUFFERS and SAMPLES are undefined.
>
>Otherwise, the value of SAMPLES is equal to the value of RENDERBUFFER_SAMPLES or TEXTURE_SAMPLES (depending on the type of the attached images), which must all have the same value. The value of SAMPLE_BUFFERS is one if SAMPLES is non-zero, and zero otherwise

So it's just a simple bug on our end. Usually, GLFW just creates a framebuffer with sample count = 2 if you request a single-sampled one, so this error never happened so far. Maybe a Windows 11 thing?

**Comment by haraldsteinlechner** [comment]
interesting. somehow it makes sense - singlesamped is not the same as no ms. no, i tried it on win11.

**Comment by haraldsteinlechner** [comment]
regarding 'a bug on our end' - where should we fix it? creating a signature with 0 samples seems weired, right?

**Comment by hyazinthh** [comment]
It's no surprise that GLFW creates windows with sample count = 2, you have to pass zero explicitly if you want to disable multisampling. Should be fixed now.

> GLFW_SAMPLES specifies the desired number of samples to use for multisampling. Zero disables multisampling. A value of GLFW_DONT_CARE means the application has no preference.

**Comment by haraldsteinlechner** [comment]
looks good

**Comment by haraldsteinlechner** [comment]
regarding error checking. using `openglapplication()` then not even performs `glGetError()` at all - historically i think think it was so, and i think at least low frequeny get-error checking should be default (fbo creation etc) - without exn, but with diagnostic output - on aardvark.log verbosity level. We often simply have no clue when getting error reports from unknown hardware somewhere in production
