### ISSUE TITLE
FontSquirrel is down, alternative? embedded free fonts with proper licences?

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.rendering#98]
![image](https://user-images.githubusercontent.com/513281/193562756-15271e79-0545-438f-b780-49552003955a.png)

**Comment by krauthaufen** [comment]
Seems to be back up again, nonetheless a Google Fonts alternative should be more reliable

**Comment by hyazinthh** [comment]
Using [Aardvark.FontProvider](https://github.com/aardvark-community/aardvark.fontprovider) starting with 5.5.0.
